let chapter7 = document.getElementById('chapter7')


 
chapter7.innerText = `

He didn’t respond to my cries as I kneeled beside him, his blood soaking my clothes. I couldn't even begin to take in all of his wounds, all the damage. One of his eyes had been yanked out of its socket along with a good chunk of flesh, leaving a huge hole on one side of his face. His entire body was bruised, cut, and bloodied, his torso looked like somebody had taken all his organs out and tried to put them back in without knowing what they were doing. One of his arms was missing, yanked out so violently it took part of his shoulder with it.

The longer I looked, the worse it got. I would have thrown up if I had anything to throw up, instead, I screamed in between sobbing, I wanted to hold him, but I was too scared to touch him and hurt him even more - I wasn’t even sure how he was still alive, he looked more like a piece of ground-up meat than a human. What had happened? Who could have done this? The rational part of me should have been afraid, but at the moment my whole being was consumed with grief that was quickly turning to white-hot anger. Just let them show up, I thought to myself,  I would do worse to them than what they had done to my father.

He stirred softly, his remaining hand tightening around something he was holding in his fist. “Dad?” I asked, but no response came. Carefully I leaned over him and pried his broken and bloody finger open, revealing what he had been holding on to. It was a small, laminated picture of me. I was around 7, and I still vividly remember the day he had taken it; we had just moved to another area and I had wanted to go to the small kids' park that the neighborhood had.

The winter day had been beautiful, and he and I had walked hand in hand to the park. It was so cold outside no other kids were playing there, something that had disappointed me as I climbed around alone. Dad must have noticed my gloomy face because he started making funny faces at me from below until I forgot all about being angry as I couldn't hold myself back from laughing. I never quite realized when he took it, only that later on I would notice he had laminated and carried it in his wallet.

A little picture of me laughing, that’s what he had been holding on to even as he lay dying.
A fresh wave of sobs shook my body but this time I tried to get myself under control. An ambulance couldn't help my dad, but maybe somebody else could. I brought my phone out with the full intention of calling the mysterious number but my dad’s hand stopped me, grabbing onto my wrist with surprising strength as his one remaining eye snapped open to look at me.

“Asher?” he asked, his voice little more than a raspy whisper, blood bubbling from his mouth. “Yes it's me, dad” I said, gripping his hand, my voice breaking as I spoke; “I'm sorry I couldn't get here before… I’m sorry, but it's okay, you are going to be okay”. I wasn’t sure who of the two I was trying to reassure with my words, but my dad clearly wasn’t buying it. “Listen to me Asher.” he said, his chest, or what remained of it, rising and falling unsteadily and he tried to breathe, “You have to run… I’m… I’m only the bait… They are coming for you… Run”.

I shook my head vigorously, tightening my grip on his hand. “I'm not leaving without you.” He coughed violently, saliva and clots of blood flying from his mouth. “Asher…” he said, his voice sounding weaker, “Look at me… I'm dying and nothing you do can fix that.” The hand I was holding me pushed me back several feet, “Go, Asher… Please… I'm begging you… If you love me, you will get the hell out of here.”

“No”, I shouted, grabbing onto his hand again, “I'm not going anywhere without you” I screamed, sobbing at him, even as I could feel his strength draining away. His eye looked at me sharply; “You stubborn boy… Sometimes I hate just how much you are like me”, he whispered, his hand freeing itself from my grasp only to caress my face, a single tear rolling down from his eye, “That was just… just what I told my mother when she lay dying many years ago.”

He paused, trying to catch his breath; “But just like how she said goodbye to me, our time to part has come.” He coughed again, a rattling sound coming from his chest. “It was a joy raising you, Asher…” he said, his voice shaky; “I love you so much, but this… this is goodbye.” His hand fell away from my face and I caught it before it could hit the floor, his eye had closed and in that moment I knew that his next breath would be his last.

I felt like something shattered within me, time seemed to slow down and my marking began burning, a sensation that morphed into a tingling feeling that began at the back of my neck and spread down my body following the path of my markings that began to glow with bright yellow light, visible even through my clothes. From the hand that still held my father I could feel the energy passing out of me and into him, the wounds in his hand glowed yellow and then healed, the effect spreading all down his arm and to his body.

With wonder I stood still, allowing energy to flow from me and into him, tendrils of yellow light flowing down his veins, healing everything in their path - even his missing arm was being mended, the outline of the limb first formed by light, then skin, bone and muscle forming around it. I wasn’t sure for how long it lasted, only that before I knew it his hand-pulled free from my grasp. He sat up slowly, looking down at his healed torso, moving his new arm, not even a scar remained anywhere on his body. “Asher…”, he said, wide-eyed, turning to look back at me. “Dad”, I breathed, fresh tears coming down my face as I tried to hug him but he pulled away, and didn’t even allow me to touch him. “Turn it off”, he said, sounding almost angry.

“What?” I asked, confused, and hurt at his rejection. I wanted to move after him but found that my legs wouldn't support my weight. “Your power Asher”, he said with urgency in his voice, “Depower, quickly”. His words made me realize that my markings were still glowing, the tingling feeling now pooling all across my body as I no longer had anything to pour it into. “I… I don't know how”, I said, my voice coming out scared. He kneeled in front of me but not close enough for me to reach out and touch him. “It’s okay… Just breath in, calm yourself down, deep breaths.”

It was hard but I did as he said, not having realized just how close to hyperventilating I had been, slowly the tingling began to become weaker and weaker the more I controlled my breathing, trying to slow down my heart that was still racing, making me feel like I had a small bird trapped inside my chest, fluttering around, desperately trying get out. Gradually the energy crawled back where it had come from, the last remnant of it fading in the back of my neck and with it, my markings stopped glowing completely.

I tried to get up again, to reach out for my father,  but the world swam in my eyes making me nauseous and I realized just how tired I felt, my muscles wouldn't even support my weight, I was completely drained. It turned out, however, that I didn’t have to move to reach him, before I knew it he had wrapped me in a hug so fierce I felt like my ribs would collapse.

“Oh Asher”, he whispered, “Asher…”

Shakily I hugged him back, crying again on his shoulder, not believing that he was real, that somehow he was still alive and with me. I wished I could have held on to him for longer but he quickly pulled away. “We have to go.” He said, urgency in his voice as he got up. “You just sent a huge flare to them, they know you are here”. I tried to get up again but failed miserably, “What… Who is them?” I said, slurring my words, it was becoming increasingly hard to keep my eyes open. “It doesn’t matter right now”, he said, running through the bloody hallway and to our coat closet that had somehow survived the worst of the disaster,  from there he pulled two thick long black jackets and two army green rucksacks.

He deposited one of the bags beside me and a jacket on my lap, “Just hold on for a little longer”, he said, “We will be out of here in no time”. Weakly I nodded at him, the movement making me even dizzier. He grabbed my phone from the floor, wiped the blood from the screen, and was in the middle of dealing a number when his eyes went wide. “How did you get here?”, he asked suddenly. “Uh…” I said, my brain slowly processing what he had said, “I… Uh… A friend drove me… Why?” His eyes turned sharply towards the door, and I followed his line of sight just in time to see the moment Deaneries fully pushing the door open - apparently she had gotten tired of waiting and despite what I had told her, had followed me here.

The color completely left her skin as she saw the horror scene that was our house, her face morphed into a mask of pure horror as she clutched her phone in her hands. We probably weren't helping the picture either, I was sitting on the floor, covered in blood and probably looking ready to pass out while my dad's clothes were next to non-existence, torn in some many places they hung around his body like fishing nets, and he was also very much dipped in blood from head to toe.

I expected her to scream to run out like a mad man, bringing down the entire neighborhood on us, instead, she just kept looking at me without blinking. She tried to say something but the words wouldn't come out, her lips shaking uncontrollably in pure shock. Before either my dad or I could react her eyes rolled to the back of her head and she fell backward, her head hitting the porch with a loud thud, her phone falling out of her hands and bouncing several times landing feet away from her now unconscious form.

My dad immediately ran towards her, for a second I was scared he would hurt her, but he simply grabbed another coat from the closer, wrapped it around her and carried her inside and towards me. “I take it this is your friend?” He asked. “Yes… that's Daenerys.” I answered, making an effort to try and focus my vision. As if awoken by me mentioning her name her eyes fully snapped open, she took one look at my father, who was carrying her bridal style, and screamed, trying to wrestle herself off his grip.

Her efforts, however, were fruitless; I heard an electrical pop, and my father's markings illuminated briefly, his with white-blue energy. It lasted less than a second, but it was enough to make Daenerys spasm and then go limp in my father's arms. “What did you do?” I asked, scared that he may have hurt her. “Just knocked her out”, he assured me, handing her over to me. I took her in my arms, unsteadily, but managed to hold on to her as my father went up the stairs and came back down less than five minutes later. He had put on clothes again though his skin was still covered in blood and he held a small paper sack in one hand. “Let's go”, he said, picking up both our bags and offering me a hand to get up.



“What are we going to do with her?”, I asked, concerned for my friend's safety, still holding on to her. “We are leaving her here”, My father said, taking her from my arms at my refusal to let her go. I frowned, “What… we can't just leave her here… and… she saw both of us… she is going to think we murdered somebody.” Dad only shook his head; “Don't worry about her memories, I already took care of it”. I shook my head, “No… We can't leave her here… not like this… In here.” I said, looking around at the bloodied room. He pinched the bridge of his nose, “Fine, I'll leave her in your room, it's clean in there.” Before he could move I grabbed onto his pants leg, “But she will still be alone.. and unconscious, what if something happened to her? What if somebody hurts her?” “Asher we don't have the time for this.” he said, pulling free from my grasp. “She will wake up in less than half an hour, she will be fine.”

I wanted to argue further, but he was already walking up the stairs leaving me behind, unable to follow him. He was back in less than a minute, his arms empty. He grabbed our two bags, the two jackets, and kneeled in front of me holding a zipped-up hoodie in his hands. “Here,” He said, helping me to put it on, making me feel like a little boy again. Not that I could complain, I could hardly keep myself awake. It took me a second to realize it was one of his own hoodies instead of mine but I didn’t mention it as he pulled me to my feet, placing one of my arms around his shoulder practically supporting all of my weight as we walked towards the front door.

The moment we stepped outside he threw the hood of my jacket on, as well as his, in an attempt to cover our bloody faces, I realized. “Uh, dad?” I asked as we walked down the porch stairs and onto the sidewalk, “Aren't we going to take the car?” I asked, looking back at our closed garage door. He shook his head, accelerating our pace making it just short of running,  “It's impregnated with our scent…” he said, “Too risky”. I frowned, trying to catch a glimpse of his face through the hood, “Then what are we…” the words died in my mouth as we got closer and closer to Daenerys parked buggy and I realized what my father was about to do.

“We aren’t-” I began, hoping I was misreading the situation but dad simply brought out the keys to the car, keys I recognized because of the black pom-pom keychain. He clicked them, unlocking the car. “We can't use our car,” he said,  “But fortunately, your friend was kind enough to leave hers behind.”
 



1:00 AM, Somewhere North




A bump in the road was what finally woke me up, making me hit my head against the car window. Slowly I opened my eyes, snapping to attention, surprised when I realized the sky outside my window was pitch black, it had still been early afternoon when I went to sleep.

“Where are we?” I asked my father, who was behind the wheel. He looked over at me briefly, the car's dashboard clock marked 1 a.m and the street was almost completely deserted, snow covering the sides of it, along with thick winter forest. “We are in the middle of Ontario”, He said.
So Canada, I thought, we were in Canada, somehow I had slept all the way from Illinois to here, little less than ten hours. “There's food in the back seat”, he offered, still not taking his eyes from the road. He didn't have to tell me twice, I reached back and brought out several bags of fast food, grease stains on the paper bags. The food was cold but I didn't care much as I devoured it, barely noticing what I was eating. All I thought about was getting rid of the pain in my stomach.

“So…” I began after I had begun to slow down, “... Where are we going?”

He sighed like he didn’t quite want to answer, but had to; “Greenland.” “Greenland?” I repeated, “Why? seems really out of the way”. A car zoomed by us, probably breaking the speed limit, “You will be safe there”, he answered simply. His words worried me, because he had said “you”, not “us”, reminding me of what had happened today, why we were on the run in the first place.
“Dad what happened to you?” I asked, “Who hurt you?” He sighed, shaking his head; “It's better if we don't talk about them here”, he answered, “They have ears everywhere, mentioning them could draw their attention.” He must have noticed my discontent at his answer, because he proceeded to explain a little more, “They want to exterminate us, Asher,” he said, “They are strong and capable and ride huge beasts who can easily kill us.”

Up until today it had been hard to imagine anything being able to kill one of us, but after what had happened to my father the possibility seemed very real.  “How… How do they look?” I asked tentatively. He frowned; “Human… they are probably more human looking than us Asher, in a crowd you wouldn’t be able to pick one out, but they are there, always watching, searching for their prey.” His words sent a shiver down my spine. “And they found you…” I whispered softly, not a question but a statement, “And it's probably my fault… They didn’t want you, didn’t they? They wanted me…”

He lapsed into silence for a while, as if thinking of how to answer, “They were looking for you”, he confirmed, “Your scent is very strong… Even though I tried to hide you as best as I could. Even putting you in school wasn’t enough and you couldn't have changed anything Asher, they have been on our trail for years, they just finally managed to catch up, it was inevitable.” I knew he was trying to not make me feel guilty about the entire thing, but even if what he said made logical sense I still felt responsible for what had happened to him. My only comfort was in that, somehow, I had managed to bring him back from the brink of death - something I still wasn’t sure how I had managed to accomplish.

“Why do they hunt us?” I asked, suddenly angry at these mysterious entities. “What do they want from us?” He seemed to almost flinch at the question; I could tell it was a sensitive topic. “Because we aren’t human, Asher”, he finally said, “Our ancestors… made mistakes, abused their power, and after they were defeated their descendants have been hunted down in fear that we will rise again to power.” Only part of his explanation registered with me, my mind having gotten stuck on the not being human part; I had always known I was different, understood that the things I could do were far from normal, but never I had always thought of myself as being human, just a different type, enhanced somehow. Part of me had always suspected it, but getting confirmation was still a lot to take in.

For some reason my mind wandered back to Dan, and how we had left her alone in the house. I wondered if she was okay, I wondered what she thought had happened to her, and above all I hoped she wouldn’t hate me, not that it looked like we would ever get the chance to see each other again. I still felt guilty for taking her car, not that dad had given me much of a choice; He had dumped me in the passenger seat and before I could even think of getting out he had started the car and we were driving away. 

I also thought of Jake, of his stupid jokes and antics, and that under it all, he was a loving and caring person who put others ahead of himself. I thought of Emma, wrestling with the wig that day, of Emilia delivering an outanding perfomace in spite of her shyness, of Theo, Yuki, Jordan, Aiden, Margarita, Brandon… and last of all, I thought of Sara, the image of her beutifull face sending a pang of pain through my chest. I would never get to see any of them again, and I realized why my mind had instantly thought of all of them. 

During the one week we had been together, I had felt more normal than any other time in my life. Spending time with them almost made me forget about the weirdness of my life, made me feel human; and now it was all gone, popped like a frail buble in the wind, one you knew wouldn't last, but had still hoped you could watch and enjoy for a little while longer. 

“So what are we?” I asked again, after a while, sounding surprisingly calm despite the turmoil inside my head. “Not here,” he said, looking around at the forest. “We already risked too much, spoke too openly.” I really couldn't see how talking about something in the middle of a highway going at almost a hundred miles an hour was dangerous - but then again, I was in the dark about a lot of stuff. “You also have to be careful about when to use your abilities.” My father added; “When we use our soul power, it's like sending a huge flare to them telling them exactly where we are.”

“Huh?” I asked, abruptly snapping out of my thoughts. “Soul power?” “When your markings shine,” he explained, “that power comes from your heart, but we call it soul energy.... Yours was yellow, so you are healer.” Well that explained a lot, I thought, but I still felt like something was nagging me about his explanation, I just couldn't put my finger on it. “I'll explain more later on.” He promised me, “About yourself, and where we are going, but we need to be careful for now. Keep your hearing sharp, if they are approaching, you will hear something that sounds like a giant heart beating, it’s impossible to miss”.

I wanted to continue our conversation, now that I had finally begun to get some answers. It seemed almost cruel to just dangle the full explanation just uot of my reach, but I also could understand my father's concern, his fear for our safety. The picture of his broken and bloodied form was still fresh in my mind, a reminder of just what could happen if we messed up even the slightest bit. If I was patient, I would get my answers, but now it was time to work. 

I expanded my hearing range to its maximum, gritting my teeth as I filtered through all the noise, keeping myself alert to anything abnormal; “Count on me.” I told my dad; “I won't let anything cach us by surprise ever again”.


More than 20 hours later, I could finally smell the sea, as we were but a few miles away from our destination, well not quite, but the end of our trip by land. A road sign written in french announced that we were less than 5 miles away from the small town of Bouctouche.

I was tired, which was weird since I hadn’t done anything except sit in a car and listen to our surroundings, I couldn't even imagine how dad was feeling, considering he had driven all twenty-something hours of the trip, but he had assure me that he was used to doing this. That, and that I had poured enough energy into him to keep him awake for a week. It was the middle of the day and the sun shone brightly above us; in this area there wasn’t much snow, most of it being in dirty piles on the sides of the road. The forest was mostly full of evergreens, but there were also other types of trees that were almost completely bare, as was to be expected considering how close to winter we were.

I rubbed my left arm subconsciously were, hours ago, after we had scrubbed the blood off of ourselves as best we could at a rest stop, dad had taken a sharpie and writen the coordinates 66.9395° N, 53.6734° W on my skin, telling me that in the event we got separated, that  was the town where I need to head to. “Once you are there, just ask anybody to point you towards the Den.” he said; “Find the place and tell them I sent you.”

I had nodded along to his instructions, committing them to memory, but I still had no intention of us getting separated at any point during this trip, not if I could help it. Dad had insisted we wore the thick winter jackets, explaining that inside the various secret pockets there was a stack of U.S and Canadian dollars, in addition to fake identities for me. Apparently he had been preparing a contingency plan for this type of situation.

The closer we got to town the more he relaxed, which also served to calm me down, it seemed we weren’t in as much danger now. My stomach rumble, reminding me it had been a while since we last ate, I was about to ask dad if we were going to eat in town when it suddenly hit me, the same sharp pain in my head I had felt before I seen that vision of the bloody curtains, of the tragedy in my home. I gripped my head in agony, bending over on the seat as I now realized part of why dad's explanation of my ability hadn’t fully made sense, or at least was missing information, if I was a healer then why was I getting visions out of nowhere?

Much like last time my vision became blurry and images flash before my eyes, images that I couldn't fully comprehend, only a few glimpses, a white harpoon flying through the air, a huge black beast dragging a body through the forest, and again, the last picture was the most clear, that of our car, Dan’s small blue buggy, thrown upside down, completely ruined and bent out of shape, a bloody trail leading away from it.

“Stop!” I shouted as soon as my head had cleared, something that was unnecessary as dad had already come to a death halt in the middle of the street. “What is it?” he asked me, gripping my shoulder anxiously; “What did you see?” I grabbed on to my door handle, “We have to get out-”, I began to say but got interrupted by a sudden pounding sound, so loud it made me cringe as I felt like the very noise was trying to break me in half.

I only saw the moment dad’s eyes widened in fear, how he reached out to try to shield me with his body as a giant black blur hit the side of our car sending it crashing into the forest with such strength that the trees broke upon impact. It all happened so fast and at the same time so slowly as we crashed through the forest, the car folding around us like it was a sheet of paper.

When we finally came to a stop we were ten meters away from the main road, the car, or what remained of it, was upside down, which meant we were also hanging down from our seat belts. I turned my head to looked toward the road, only to witness a terrifying sight, there was a huge beast standing in the middle of it, the only word I could think to describe it was a dragon, covered from head to toe in tick black armor, it must had been the size of a large truck with spikes behind its head and on the tip of its long flat tail. It seemed to have no mouth or eyes but that only made it more terrifying.

The world seemed to freeze as the creature caught sight of us, despite its lack of eyes I almost felt like it was looking into my very soul, sending a shiver down my spine, for what seemed seconds, but also an eternity  we only  looked at each other in silent challenge. Just as fast as it had happened, the spell broke and I unbuckled my seatbelt as the creature charged towards us like a barreling mountain of destruction,  it's form blurring with speed, and, before I knew it, before I could even brace myself,  it was upon us.  


`